[package]
name = "mc-verifier"
version = "0.1.0"
authors = ["Aaron Hill <aa1ronham@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "0.2.0-alpha.6"
byteorder = "1.3.2"
packet_macro = { path = "packet_macro" }
lazy_static = "1.4.0"
bytes = "0.4.12"
openssl = "0.10.25"
#hyper = { git = "https://github.com/hyperium/hyper" }
#hyper-tls = { git = "https://github.com/hyperium/hyper-tls" }
num-bigint = "0.2.3"
libc = "0.2.62"
futures-preview = { version = "0.3.0-alpha.19", features = ["async-await", "compat"] }
json = "0.12.0"
stream-cancel = "0.5.0-alpha.4"
uuid = { version = "0.7.4", features = ["serde"] }
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
base64-serde = "0.3.2"
base64 = "0.10.1"
#termimage = "0.4.0"
termimage = { git = "https://github.com/Aaron1011/termimage", rev = "update/image" }
image = "0.22.3"
env_logger = "0.7.0"
term_size = "1.0.0-beta1"
chrono = "0.4.9"
atomicbox = "0.2.0"
futures-async-stream = "0.1.0-alpha.7"
failure = "0.1.5"
hyper = {version = "0.13.0-alpha.4", features = ["unstable-stream"] }
hyper-tls = "0.4.0-alpha.4"

[dev-dependencies]
criterion = "0.3.0"

[[bench]]
name = "creation_time"
harness = false
