[package]
name = "mc-verifier"
version = "0.1.0"
authors = ["Aaron Hill <aa1ronham@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "0.2.0-alpha.4"
byteorder = "1.3.2"
packet_macro = { path = "packet_macro" }
lazy_static = "1.4.0"
bytes = "0.4.12"
openssl = "0.10.24"
hyper = { git = "https://github.com/hyperium/hyper" }
hyper-tls = { git = "https://github.com/hyperium/hyper-tls" }
num-bigint = "0.2.2"
libc = "0.2.62"
futures-preview = { version = "0.3.0-alpha.18", features = ["async-await", "nightly", "compat"] }
json = "0.11.15"
stream-cancel = "0.4.4"
uuid = { version = "0.7.4", features = ["serde"] }
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"
base64-serde = "0.3.2"
base64 = "0.10.1"
termimage = "0.4.0"
image = "0.21"
env_logger = "0.6.2"
term_size = "1.0.0-beta1"
chrono = "0.4.7"
atomicbox = "0.2.0"
futures-async-stream = "0.1.0-alpha.5"

[dev-dependencies]
criterion = "0.3.0"

[[bench]]
name = "creation_time"
harness = false
