[package]
name = "mc-verifier"
version = "0.1.0"
authors = ["Aaron Hill <aa1ronham@gmail.com>"]
edition = "2018"

[dependencies]
#tokio = { path = "../tokio" }  #"0.1.16"
#tokio = { path = "../tokio" }  #"0.1.16"
tokio = "0.1.17"
byteorder = "1.3.1"
packet_macro = { path = "packet_macro" }
lazy_static = "1.3.0"
bytes = "0.4.12"
openssl = "0.10.19"
hex = "0.3.2"
hyper = "0.12.25"
hyper-tls = "0.3.1"
env_logger = "0.6.1"

#[patch.crates-io]
#tokio = { path = "../tokio" }

[replace]
"tokio:0.1.17" = { path = "../tokio" }
"tokio:0.1.12" = { path = "../tokio" }
"tokio-executor:0.1.6" = { path = "../tokio/tokio-executor" }
"tokio-timer:0.2.10" = { path = "../tokio/tokio-timer" }
"tokio-threadpool:0.1.12" = { path = "../tokio/tokio-threadpool" }
"tokio-tcp:0.1.3" = { path = "../tokio/tokio-tcp" }
"tokio-sync:0.1.4" = { path = "../tokio/tokio-sync" }
"tokio-reactor:0.1.9" = { path = "../tokio/tokio-reactor" }
"tokio-io:0.1.12" = { path = "../tokio/tokio-io" }
