[package]
name = "packet_macro"
version = "0.1.0"
authors = ["Aaron Hill <aa1ronham@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.3"
proc-macro2 = "1.0.9"

[dependencies.syn]
version = "1.0.16"
features = ["full", "extra-traits"]
